SELECT A.ITEM_ID, A.ITEM_NAME, A.RARITY
FROM ITEM_INFO A
WHERE ITEM_ID NOT IN (
    SELECT PARENT_ITEM_ID
    FROM ITEM_TREE B
    WHERE EXISTS (
        SELECT 1
        FROM ITEM_INFO
        WHERE ITEM_ID = PARENT_ITEM_ID
    )
)
ORDER BY ITEM_ID DESC
;