-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM SALES_DATE) YEAR, EXTRACT(MONTH FROM SALES_DATE) MONTH,
COUNT(DISTINCT S.USER_ID) PUCHASED_USERS, ROUND(COUNT(DISTINCT S.USER_ID) / MAX(CNT), 1) PUCHASED_RATIO 
FROM (
    SELECT USER_ID, COUNT(USER_ID) OVER() CNT
    FROM USER_INFO 
    WHERE EXTRACT(YEAR FROM JOINED) = '2021'
) A
LEFT OUTER JOIN ONLINE_SALE S
ON S.USER_ID = A.USER_ID
GROUP BY EXTRACT(YEAR FROM SALES_DATE), EXTRACT(MONTH FROM SALES_DATE)
HAVING COUNT(S.USER_ID) > 0