SELECT CONCAT("/","home/grep/src","/",USED_GOODS_BOARD.BOARD_ID,"/",FILE_ID,FILE_NAME, FILE_EXT)FILE_PATH
FROM USED_GOODS_BOARD, USED_GOODS_FILE
WHERE USED_GOODS_BOARD.BOARD_ID = USED_GOODS_FILE.BOARD_ID
AND VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
order by FILE_ID desc